### ISSUE TITLE
Ability to switch zoom functionality off

### ISSUE THREAD

**Issue by amalitsky** [igordanchenko/yet-another-react-lightbox-lite#2]
### Is your feature request related to a problem? Please describe.

Would like to disable zoom via props. Looks like there is an interface [`ZoomSettings`](../blob/main/src/types.ts#L142), but it's not yet used or passed to [`Zoom`](../blob/main/src/components/Zoom.tsx#L55) component it seems.

Why would I like to switch it off? Because I don't expect zoom behavior on dblclick. Migrating from _react-image-lightbox_. Thanks for the awesome alternative btw! Very helpful and timely. Also looks like it's very well designed and written.

### Describe the solution you'd like

I guess `Zoom` component needs to receive `props.zoom` and probably have one more property to turn it off completely. Rather than passing an empty list for `zoom.supports`.

**Comment by igordanchenko** [comment]
Hi there! Indeed, there is currently no way to disable zoom on image slides. I'll add a config option for this.

> Looks like there is an interface [ZoomSettings](https://github.com/igordanchenko/yet-another-react-lightbox-lite/blob/main/src/types.ts#L142), but it's not yet used or passed to [Zoom](https://github.com/igordanchenko/yet-another-react-lightbox-lite/blob/main/src/components/Zoom.tsx#L55) component it seems.

`zoom` prop (that is of `ZoomSettings` type)  is actually accessed here:

https://github.com/igordanchenko/yet-another-react-lightbox-lite/blob/c5e3a62f38fb76968d1654759800b3b938c0819b/src/components/Zoom.tsx#L64

> Rather than passing an empty list for zoom.supports.

Unfortunately, an empty array didn't disable zoom on the default image slides.

**Comment by amalitsky** [comment]
Wow, thanks a lot for the instant fix AND release. 🙌

Will try later today
