### ISSUE TITLE
Ability to go to the first slide after the last

### ISSUE THREAD

**Issue by amalitsky** [igordanchenko/yet-another-react-lightbox-lite#3]
### Is your feature request related to a problem? Please describe.

Not sure what the correct term is, but I'd like to have an "endless" carousel, where after clicking _Next_ button on the last image, I can see the _First_ image. And vice versa - _Previous_ button on the _First_ image would take user to the _Last_ image.

So that I could mindlessly sit clicking that _Next_ button on and on and enjoy my own photos.

Currently _Next_ and _Prev_ buttons are [disabled](../blob/main/src/components/Navigation.tsx#L21) when rendering first or last image. Also it seems like Controller's `prev` and `next` methods don't support jumping through start/end.

### Describe the solution you'd like

Configuration nob (prop) would be ideal.

### Describe alternatives you've considered

I can probably use `render.iconPrev` and `iconNext` for the same and that's a legit solution. :beers: 

### Additional context

Still loving the lib! Love the configurability of everything through CSS props and render functions.

**Comment by igordanchenko** [comment]
One of the design goals for this library was to create a lightweight version of the [yet-another-react-lightbox](https://github.com/igordanchenko/yet-another-react-lightbox) library. In order to achieve this goal, a number of features were deliberately left behind. Infinite carousel was one of those features that didn't make the cut.

However, you can implement the desired behavior in the user land.

```tsx
<>
  <Lightbox
    index={index}
    slides={[slides[slides.length - 1], ...slides, slides[0]]}
    setIndex={(newIndex) => {
      if (newIndex === 0) {
        setIndex(slides.length);
      } else if (newIndex === slides.length + 1) {
        setIndex(1);
      } else {
        setIndex(newIndex);
      }
    }}
  />

  <button type="button" className="button" onClick={() => setIndex(1)}>
    Open Lightbox
  </button>
</>
```

**Comment by amalitsky** [comment]
Fair enough, I completely understand the need to limit number of options and behaviors in a reusable library.

Thanks for the snippet above - it's smart and does the trick, but IMO is not very elegant, declarative or clear for someone who might stumble upon this code in a future within my (user's) code-base.

I also just realized that there is no way to pass a custom next/prev button render functions, only custom icons can be provided.
That means that I can't override `disable` behavior and call `setIndex` callback on their click.

I can probably render extra buttons via `controls` or `header` render functions, and then hide default prev/next buttons with css, but that's not very elegant either. :thinking: 

May be introducing customizable next/prev render function props is a happy medium? Even from customization perspective this might make sense for more than one humble user.

**Comment by igordanchenko** [comment]
> Thanks for the snippet above - it's smart and does the trick, but IMO is not very elegant, declarative or clear for someone who might stumble upon this code in the future within my (user's) code-base.

Well, I guess it's a matter of personal taste. IMO, it's a very concise and elegant approach to extend a 3rd-party library with desired functionality. Also, well-written comments accompanying the non-trivial parts of the code always help avoid future confusion. 

> I can probably render extra buttons via controls or header render functions, and then hide default prev/next buttons with css, but that's not very elegant either. 🤔

You are overlooking the fact that navigation buttons are just one of the four supported slide navigation controls. By rendering your custom navigation buttons, you will not change the keyboard navigation logic, click-and-drag, and touch-swipe, which will not provide the desired navigation functionality on the first and the last slide.

**Comment by amalitsky** [comment]
Right, good point about keyboard and gesture navigation events! Forgot about those.

Also preload of adjacent images is a factor.

I guess `setIndex` with a different argument signature could work (i.e. `action: previous` or `action: next` instead of an `index`), but then buttons won't ever get disabled, unless more callbacks (such as `disableNext` and `disablePrevious`) are introduced. Which is not ideal.

Thanks for the conversation and library.
